### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by TKlerx** [EdwardRaff/JSAT#4] opened 2015-04-09 07:03 UTC
The following tests fail with windows and jdk 1.8 (I don't think this is windows or java related ;) ):

Failed tests: 
  ElkanKMeansTest.testCluster_3args_2:106 expected:`<3>` but was:`<4>`
  RandomBallCoverTest.testSearch_Vec_double:114 jsat.linear.vectorcollection.RandomBallCover$RandomBallCoverFactory failed expected:`<14>` but was:`<13>`
  RandomBallCoverTest.testSearch_Vec_int:168 jsat.linear.vectorcollection.RandomBallCover$RandomBallCoverFactory failed 10
  VPTreeMVTest.testSearch_Vec_int:171 jsat.linear.vectorcollection.VPTreeMV$VPTreeMVFactory failed 10
  VPTreeTest.testSearch_Vec_double:113 jsat.linear.vectorcollection.VPTree$VPTreeFactory failed expected:`<12>` but was:`<11>`
  VPTreeTest.testSearch_Vec_int:167 jsat.linear.vectorcollection.VPTree$VPTreeFactory failed 1
  FastMathTest.testPow:152 null

EDIT:
It seems that some of the tests sometimes fail and sometimes pass. I did not have a closer look but maybe there are some random issues in the tests.
This time I got the following result:

Failed tests: 
  NewGLMNETTest.testSetC:109 null
  ElkanKMeansTest.testCluster_3args_2:106 expected:`<3>` but was:`<4>`
  NaiveKMeansTest.testCluster_3args_1:89 expected:`<10>` but was:`<9>`
  RandomBallCoverTest.testSearch_Vec_double:114 jsat.linear.vectorcollection.RandomBallCover$RandomBallCoverFactory failed expected:`<14>` but was:`<7>`
  RandomBallCoverTest.testSearch_Vec_int:168 jsat.linear.vectorcollection.RandomBallCover$RandomBallCoverFactory failed 20
  VPTreeMVTest.testSearch_Vec_double:114 jsat.linear.vectorcollection.VPTreeMV$VPTreeMVFactory failed expected:`<13>` but was:`<0>`
  VPTreeMVTest.testSearch_Vec_int:171 jsat.linear.vectorcollection.VPTreeMV$VPTreeMVFactory failed 2
  VPTreeTest.testSearch_Vec_double:113 jsat.linear.vectorcollection.VPTree$VPTreeFactory failed expected:`<13>` but was:`<0>`
  VPTreeTest.testSearch_Vec_int:167 jsat.linear.vectorcollection.VPTree$VPTreeFactory failed 1
Tests in error: 
  PegasosKTest.testTrainC_ClassificationDataSet_ExecutorService:68 » FailedToFit
  DivisiveGlobalClustererTest.testCluster_DataSet_int_int_ExecutorService:129 » ArrayIndexOutOfBounds
  MiniBatchKMeansTest.testCluster_3args_1:94 » IndexOutOfBounds Index: 0, Size: ...

**Comment by EdwardRaff** [comment] 2015-04-09 14:12
>It seems that some of the tests sometimes fail and sometimes pass. I did not have a closer look but maybe there are some random issues in the tests.

Unfortunately many of the algorithms don't have guaranteed behavior & rely on randomness, so that does happen. I've tried to make most of the tests pass pass as often as possible by giving them simple problems to solve that they *should* be able to solve perfectly most of the time. But because there is a random nature to many of the algorithms, it doesn't always happen. 

I'm currently working on going through and improving the test coverage and consistency. 

I'd only be worried about a test that gave an error (like PegasosK) - so I'll investigate those that look like they are sometimes failing in *working* rather than sometimes giving the wrong answer.

**Comment by davidmoten** [comment] 2015-04-13 21:19
Edward I get failures when I build the library too (see below). What you could do is loop the non-guaranteed behaviour tests n times and they pass as soon as a loop passes and only fail if all n fail. With high enough n that will turn the "mostly passes" test into a close to deterministic "nearly always passes".

```
StackingTest.testRegressionMT:177 expected:<0.0> but was:<-0.031187905891321883>
  RandomForestTest.testTrainC_RegressionDataSet_ExecutorService:107 null
  StochasticRidgeRegressionTest.testTrainC_RegressionDataSet_ExecutorService:98 null
```

**Comment by EdwardRaff** [comment] 2015-04-13 22:31
@davidmoten That is my intention yes. My first goal was to increase coverage, then go back and deal with inconsistent tests. My hope was Junit might have a functionality where I could provide an annotation like

```
@Test
@Trials(n=20, min=15)
public void smomeMethod() {
}
``` 

But I haven't looked into that yet.

**Comment by TKlerx** [comment] 2015-04-14 08:27
I had a closer look at the ElkanKMeansTest and if I understand the result correctly, sometimes not all of the points in one cluster have the same class attribute assigned by the algorithm.
This is not a minor bug or whatever, but just wrong.

In the NaiveKMeansTest sometimes the algorithm creates 9 and sometimes 10 clusters.

This only happens when using the ExecutorService. So running the algorithms in parallel is not a good idea because you cannot trust the result!
Any remarks/ideas how to fix this (if even possible)?

**Comment by EdwardRaff** [comment] 2015-04-14 13:28
@TKlerx Please list your exact java version & environment. I just ran all of the k-means package 30 times with 0 failures. 

>sometimes not all of the points in one cluster have the same class attribute assigned by the algorithm.
This is not a minor bug or whatever, but just wrong.

How is that wrong? The class attribute is the true cluster. All the points should end up in the true cluster should end up in the same k-means cluster. 

>In the NaiveKMeansTest sometimes the algorithm creates 9 and sometimes 10 clusters.

>This only happens when using the ExecutorService. So running the algorithms in parallel is not a good idea because you cannot trust the result!

K-Means is again *not* a deterministic algorithm. Creating 9 clusters instead of 10 would not be an indication of the algorithm being wrong (even though I'm not able to reproduce that problem). The method of determining the number of clusters is a very simple and naive approach anyway, it exists mostly for convenience. 

In general, you can *never* trust any machine learning algorithm, its not like a regular algo class were you can guarantee you will always get a specific result for any given input.

**Comment by TKlerx** [comment] 2015-04-14 13:50
Environment/Java: Windows 8.1 x64, Java 1.8 u25 x64
ElkanKMeansTest fails in line 106, where it checks whether all points from one cluster have the same cluster index (or am I mistaken on this?).

I know that K-Means is not a deterministic algorithm, *but* if you initialize it with the same randomseed etc. the result should always be the same.
I think I have not been clear about what is wrong. Of course, you cannot trust any machine learning that it gives you the optimal result (for some inputs with specific assumptions, the result may be the optimal one).
The point I want to make is that running the algorithm in parallel may give you other results than running the algorithm sequential for the same input *and* the same random seed. Even worse (in my environment) running the algorithm in parallel with the same random seed may yield different results.
As I am using JSAT for research, my experiments need to be repeatable (with probability one) and that is not the case when run in parallel.

**Comment by EdwardRaff** [comment] 2015-04-14 13:58
>Environment/Java: Windows 8.1 x64, Java 1.8 u25 x64

I don't have a Window 8 box to test with, but please update to 1.8u40 

 >ElkanKMeansTest fails in line 106, where it checks whether all points from one cluster have the same cluster index (or am I mistaken on this?).

Yes, that is the way it *should* work. We have 10 true clusters, each with an id in [0, 9]. If we have correctly recovered all 10 clusters, each cluster we recover should have 1 and only 1 id in it. 

>I know that K-Means is not a deterministic algorithm, but if you initialize it with the same randomseed etc. the result should always be the same.

The data set is initialized with a fixed seed (for this test). The SeedSelectionMethod used by k-means is not, and is using a different random seed each time. 

>The point I want to make is that running the algorithm in parallel may give you other results than running the algorithm sequential for the same input and the same random seed.

This is not the case and hasn't been observed, since the SeedSelectionMethod is still introducing some randomness.

**Comment by TKlerx** [comment] 2015-04-14 14:19
>The data set is initialized with a fixed seed (for this test). The SeedSelectionMethod used by k-means is not, and is using a different random seed each time. 
Can you tell me the line where you introduce an additional random seed for the SeedSelectionMethod when using running this test? Maybe I am just wrong, but I don't find it.

**Comment by EdwardRaff** [comment] 2015-04-14 18:02
If you look at Elkan's constructor, you can pass in the Random object that will be used 

```
public ElkanKMeans(DistanceMetric dm, Random rand, SeedSelection seedSelection)
```

However, most of the classes in JSAT don't take a Random obj in their constructor even if they need randomness. Adding an interface for getting/setting a seed is one of my many TODOs if you need *very* strict control to reproduce the exact same results. However no one has approached me asking for such functionality so I've not made any effort to put it in. 

If you wanted to force a specific repeatable behavior for all methods tat use SeedSelection, you could modify the SeedSelectionMethods class to ignore the passed in object and always use its own with a fixed seed.

**Comment by TKlerx** [comment] 2015-04-15 06:34
Let's just talk about the ElkanKMeansTest for now (in other classes no Random obj is passed so of course these tests produce different results for different runs).

I updated to Java 1.8u45, but still no change. If I run the ElkanKMeansTest from eclipse, it always works, but called from Maven (with all other tests), it fails.
>If you wanted to force a specific repeatable behavior for all methods tat use SeedSelection, you could modify the SeedSelectionMethods class to ignore the passed in object and always use its own with a fixed seed. 

I don't understand your suggestion. 
If you pass the Random object to ElkanKMeans, then this Random object is used in the following methods:
```java
static public List<Vec> selectIntialPoints(DataSet d, int k, DistanceMetric dm, List<Double> accelCache, Random rand, SeedSelection selectionMethod, ExecutorService threadpool)
static public void selectIntialPoints(DataSet d, int[] indices, DistanceMetric dm, List<Double> accelCache, Random rand, SeedSelection selectionMethod, ExecutorService threadpool)
private static void ffSelection(final int[] indices, Random rand, final DataSet d, final int k, final DistanceMetric dm, final List<Double> accelCache, ExecutorService threadpool) throws InterruptedException, ExecutionException
```

That should be more or less the call trace for the ElkanKMeansTest.
So my question is:
If you always use the same Random object which returns the same "random" results for any execution, then why are the results different for different runs?
I suppose that it is the concurrency which introduces non-determinism (or a bug in java ;) ).
The test without parallel execution always passes.

**Comment by EdwardRaff** [comment] 2015-04-16 04:36
>I updated to Java 1.8u45, but still no change. If I run the ElkanKMeansTest from eclipse, it always works, but called from Maven (with all other tests), it fails.

I don't know how, but somehow your environment is altering the PRNG initialization despite a seeded object. 

For Elkan, I will try to explicitly explain what I'm quite sure is going on. 

You have a seed selection method that must be run for k-means, and k-means solution is dependent upon the initial seeds. The test implementation used *one* object for *two* tests. So the Seeds used in each test *are* different, because we can't roll back or get the seed of a Random object after the fact. So when one fails and the other passes, its *not* a bug that is giving you different solutions for the *same* seeds. You are getting *different solutions for different seeds*, because you can see that the Elkan object is created in the SetUp method annotated with *"BeforeClass"*. 

Its not an artifact of the Multi-threaded version being buggy (so far as I've yet to find any such bug). Now, the values were seeded - why you appear to be getting different values out of the same seed is a loss to me. But I don't have time to deal with such strangeness. 

Now, to convince you - I've altered the test cases for the k-means based methods in commit 2679a1b456353d10060ceac14883d78bac909884 , and I give them explicit starting seeds that are near but off-set from the expected final location. I've run this 20 times on the 5 machines I have available to me and have no failures. 

Do you understand now? 

As for your additional spurious failures. As I said, *I'm aware*. Posting more does not help me. As I said, my plan is to *first* increase test coverage and *then* deal with spurious failures caused by randomness. Again, this is a free time project for me - its going to take some time.

**Comment by TKlerx** [comment] 2015-04-16 06:21
First of all, I want to apologize if I was rude. I like your library and your work, and I am grateful that you implemented all of these algorithms in your free time.
It was not my intention to bug you with more failure traces. I thought that it might be good for the future to know which tests failed in the past.

>You have a seed selection method that must be run for k-means, and k-means solution is dependent upon the initial seeds. The test implementation used one object for two tests. So the Seeds used in each test are different, because we can't roll back or get the seed of a Random object after the fact. 

You are right. I did not see that.

>Now, to convince you - I've altered the test cases for the k-means based methods in commit 2679a1b , and I give them explicit starting seeds that are near but off-set from the expected final location. I've run this 20 times on the 5 machines I have available to me and have no failures. 

I am sorry but the tests still fail in 50% of the cases. I added fixed Random seeds to your <XORWOW>, but still.
The test still fails if I *only* run the <testCluster_3args_2()> test in <ElkanKMeansTest> (so just this one test method).

I understand that you do not want to deal with this strange behaviour, so I will try to figure this out by myself. As all the tests without parallel execution pass, I still suspect the parallel execution to cause this behavior.

But anyway, again: You are doing a great job in your free time. Sorry, if I was rude.

**Comment by EdwardRaff** [comment] 2015-04-18 02:46
Sorry, you weren't rude. I was just a bit frustrated and have been a bit under the weather. 

>I am sorry but the tests still fail in 50% of the cases.

I can't replicate this at all. If you want to email me and give me SSH access I can try and debug remotely, but otherwise I'm not sure what else I can do for that one.

**Comment by TKlerx** [comment] 2015-04-18 18:36
I can only give you teamviewer access since the machine is behind a firewall.
Is teamviewer ok for you?

**Comment by EdwardRaff** [comment] 2015-04-18 19:12
I'm not familiar with team viewer. Send me an email with the details and we can figure it out

**Comment by EdwardRaff** [comment] 2015-05-26 13:46
@TKlerx confirmed the KMeans one is passing now consistently. Since this this is otherwise a bit of a mess I'm closing it.

**Closed by EdwardRaff** 2015-05-26 13:46 UTC
